import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'

const interDisplay = localFont({
  src: '../public/fonts/InterDisplay-Medium.woff2',
  variable: '--font-display',
})
const inter = Inter({ subsets: ['latin'], variable: '--font-body' })

const ppMori = localFont({
  src: '../public/fonts/PPMori-SemiBold.otf',
  variable: '--font-ppmori',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${interDisplay.variable} ${ppMori.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      {children}
      </body>
    </html>
  );
}
